version: '3'

services:
  machine-learning:
    image: luisdavidparra/ml-service:$TAG_PROD
    container_name: ml-service
    restart: always
    ports:
      - 3000:3000
      - 3001:3000
    environment:
      PORT: 3000
      SERVER_URL: http://localhost:3000/api/v1

volumes:
  ml-service:

networks:
  ml-service:
  